[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib", "staticlib"]
name = "pkarrbindings"
 
[dependencies]
pkarr = { version = "1.1.0", features = ["async"] }
uniffi = { version = "0.25.3", features = [ "cli" ] }
