[package]
name = "pkarr"
version = "2.3.0"
authors = ["Nuh <nuh@nuh.dev>"]
edition = "2021"
description = "Public-Key Addressable Resource Records (Pkarr); publish and resolve DNS records over Mainline DHT"
license = "MIT"
repository = "https://git.pkarr.org"
keywords = ["mainline", "dht", "dns", "decentralized", "identity"]
categories = ["network-programming"]

[dependencies]
bytes = "1.9.0"
document-features = "0.2.10"
ed25519-dalek = "2.1.1"
self_cell = "1.1.0"
thiserror = "2.0.9"
tracing = "0.1.41"
z32 = "1.1.1"
rand = { version = "0.8.5", optional = true }
lru = { version = "0.12.5", default-features = false }
flume = { version = "0.11.1", features = ["select", "eventual-fairness"], default-features = false }
hickory-proto = "0.24.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# Dht client dependencies:
mainline = { version = "2.0.1", optional = true }
dyn-clone = { version = "1.0.17", optional = true }

# Relay client dependencies
ureq = { version = "2.12", default-features = false, features = ["tls"], optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures = "0.3.31"
js-sys = "0.3.76"
wasm-bindgen = "0.2.99"
wasm-bindgen-futures = "0.4.49"
web-sys = { version = "0.3.76", features = [
  "console",
  "Request",
  "RequestInit",
  "RequestMode",
  "Response",
  "Window",
] }

[dev-dependencies]
futures = "0.3.31"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
clap = { version = "4.5.24", features = ["derive"] }
mockito = "1.6.1"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.49"

[features]
## Use [PkarrClient]
dht = ["dep:mainline", "dep:dyn-clone"]
## Use [Keypair::random]
rand = ["dep:rand", "ed25519-dalek/rand_core"]
## Use async versions of [PkarrClient] and/or [PkarrRelayClient]
async = ["flume/async"]
## Use [PkarrRelayClient]
relay = ["dep:ureq"]
## Use all features
full = ["dht", "async", "relay", "rand"]

default = ["dht", "rand"]

[package.metadata.docs.rs]
all-features = true
