[package]
name = "pkarr-relay"
version = "0.1.0"
authors = ["Nuh <nuh@nuh.dev>"]
edition = "2021"
description = "Pkarr relay (https://pkarr.org/relays)"
license = "MIT"
repository = "https://git.pkarr.org"
keywords = ["pkarr", "relay", "mainline", "dht"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.93"
axum = "0.7.9"
tokio = { version = "1.41.1", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
axum-server = { version = "0.7.1", features = ["tls-rustls-no-provider"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
http = "1.1.0"
thiserror = "2.0.3"
bytes = "1.9.0"
tower_governor = "0.4.3"
governor = "0.6.3"
serde = { version = "1.0.215", features = ["derive"] }
toml = "0.8.19"
clap = { version = "4.5.21", features = ["derive"] }
dirs-next = "2.0.0"
pkarr = { version = "3.0.0", path = "../pkarr", features = ["dht", "lmdb-cache"] }
httpdate = "1.0.3"
pubky-timestamp = { version = "0.2.0", features = ["httpdate"] }
mainline = { workspace = true }
