on:
  push:
    tags:
      - 'v*.*.*'

permissions:
      contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: pubky/ci-workflows/.github/actions/docker/build_and_push@main
        with:
          registry: registry-1.docker.io/synonymsoft
          context: .
          push: true
          latest: true
          tags: |
            type=ref,event=tag
          platforms: |
            linux/arm64
            linux/amd64
          image: pkarr-relay
          cache_from: type=gha
          cache_to: type=gha,mode=max
